language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t bouyagas/docker-react -f Dockerfile.dev .


scripts:
  - docker run -e CI=true bouyagas/docker-react npm run test
